language: ruby
rvm:
  - 2.4.1

before_script:
  - chmod +x ./scripts/cibuild

script: ./scripts/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
sudo: false

cache: bundler

notifications:
  email: false