
# SEO settings
title: "biblio"
title2: "graphy" # default: ""
description: ""
keywords: ""
url: http://molguin92.github.io/bibliography # site url
baseurl: "/bibliography" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/molguin92/bibliography
disqus_shortname: ""
twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Manuel Olguín"
  job      : "PhD student @ KTH Royal Institute of Technology"
  bio      : ""
  thumb    : /images/author.jpg
  email    : molguin@kth.se
  url      : http://molguin92.github.io
  github   : http://github.com/molguin92
  twitter  : http://twitter.com/molguin92
  # facebook : https://www.facebook.com/heiswayi.nrird
  linkedin : http://linkedin.com/in/molguin92

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@molguin92"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
