#!/usr/bin/env bash

git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"

git clone https://${GH_TOKEN}@github.com/molguin92/bibliography.git ./_gh_pages > /dev/null 2>&1

cd ./_gh_pages
git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
git fetch --all
git checkout -b gh-pages --track origin/gh-pages
git pull

rsync -a -v ../_site/ ./
git add .
git commit -m "Travis build: $TRAVIS_BUILD_NUMBER"

git push -u origin gh-pages